services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    container_name: myapp-server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    container_name: myapp-client
    depends_on:
      - server